### PR TITLE
Fix formatting issues in retrieve secrets script

### PR DESCRIPTION
**Pull request by BradleyBoutcher**
### What does this PR do?
Resolves several codeclimate issues 
in our secret retrieval script

### What ticket does this PR close?
-

#### Change log
- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [X] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [X] This PR does not require updating any documentation

### CODE REVIEW

**Review by izgeri — APPROVED** [review]

**Comment by izgeri** [comment]
@BradleyBoutcher there are still errors for the `BASH_SOURCE` line changes:
```
Argument mixes string and array. Use * or separate argument. 
```

**Review by izgeri — APPROVED** [review]
LGTM, pending green build

**Review by diverdane — COMMENTED** [review]
While we're cleaning up, there are a couple of CC complaints that say it would like nested double quotes on lines 59 and 73.

**Review by diverdane — APPROVED** [review]
LGTM!

**Pull request merged**
